name: Deploy to Minikube using GitHub Actions

on: [push]

env:
  IMAGE_NAME: devopshint/node-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Minikube
        uses: medyagh/setup-minikube@v0.0.19
      
      - name: Verify cluster connectivity
        run: kubectl get pods -A
      
      - name: Build Docker image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          echo "Built image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          docker images | grep node-app
      
      - name: Deploy to Minikube
        run: |
          sed "s|devopshint/node-app:latest|${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" k8s-node-app.yaml | kubectl apply -f -
      
      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/nodejs-app --timeout=180s
      
      - name: Get diagnostic info
        if: always()
        run: |
          echo "=== Pod Status ==="
          kubectl get pods -o wide
          echo "=== Service Status ==="
          minikube service list
          echo "=== Service URL ==="
          minikube service nodejs-app --url
