name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest

      - name: Verify cluster connectivity
        run: kubectl get pods -A

      - name: Build Docker image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          IMAGE_TAG=${{ github.sha }}
          docker build -f ./Dockerfile -t devopshint/node-app:${IMAGE_TAG} .
          echo "Built image devopshint/node-app:${IMAGE_TAG}"
          echo -n "Verifying images:"
          docker images

      - name: Deploy to Minikube
        run: |
          IMAGE_TAG=${{ github.sha }}
          sed "s|devopshint/node-app:latest|devopshint/node-app:${IMAGE_TAG}|g" k8s-node-app.yaml | kubectl apply -f -

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/nodejs-app --timeout=180s

      - name: Diagnostic info (optional)
        run: kubectl get pods -o wide || true

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
